### ISSUE TITLE
Error in generating generateStatsFig when running example dataset

### ISSUE THREAD

**Issue by Eldonoho99** [riboviz/example-datasets#109]
Having an issue with running the Wallace et al. 2020 Cryptococcus neoformans 'JEC21' example dataset. Problem occurs at the generateStatsFig step. 

The yaml file is [example-datasets](https://github.com/riboviz/example-datasets)/[fungi](https://github.com/riboviz/example-datasets/tree/main/fungi)/[cryptococcus](https://github.com/riboviz/example-datasets/tree/main/fungi/cryptococcus)/Wallace_2020_JEC21_2-samples_10p_up12dwn9_CDS_120bpL_120bpR_config.yaml. 

The job submission file is the one specified in the https://github.com/riboviz/riboviz/blob/main/docs/user/run-on-eddie.md. 

Nextflow output:

[f6/1b02ab] Submitted process > cutAdapters (JEC21)
[06/6a45f1] Submitted process > cutAdapters (JdAGO1)
[eb/1209f2] Submitted process > buildIndicesrRNA (JEC21_rRNA)
[fb/12b3a5] Submitted process > buildIndicesORF (JEC21_CDS_with_120bputrs)
[a0/5b9e90] Submitted process > createVizParamsConfigFile
[93/40ec82] Submitted process > createInteractiveVizParamsConfigFile
[9c/ca3b3c] Submitted process > hisat2rRNA (JdAGO1)
[ae/eccb92] Submitted process > hisat2rRNA (JEC21)
[12/02dd93] Submitted process > hisat2ORF (JdAGO1)
[8a/c2a077] Submitted process > hisat2ORF (JEC21)
[82/78b029] Submitted process > trim5pMismatches (JdAGO1)
[c5/baf90f] Submitted process > samViewSort (JdAGO1)
[41/2bfc20] Submitted process > trim5pMismatches (JEC21)
[1e/a29aba] Submitted process > outputBams (JdAGO1)
[60/c44fbd] Submitted process > makeBedgraphs (JdAGO1)
[16/409314] Submitted process > bamToH5 (JdAGO1)
[cf/ba0263] Submitted process > generateStatsFigs (JdAGO1)
[23/f97bd5] Submitted process > samViewSort (JEC21)
[cf/ba0263] NOTE: Process `generateStatsFigs (JdAGO1)` terminated with an error exit status (1) -- Error is ignored
[f6/7e9f99] Submitted process > outputBams (JEC21)
[bf/aeca92] Submitted process > makeBedgraphs (JEC21)
[95/55e810] Submitted process > bamToH5 (JEC21)
[87/eda624] Submitted process > generateStatsFigs (JEC21)
[87/eda624] NOTE: Process `generateStatsFigs (JEC21)` terminated with an error exit status (1) -- Error is ignored

The .command.err for [cf/ba0263] contains the following information

`summarise()` ungrouping output (override with `.groups` argument)
`summarise()` ungrouping output (override with `.groups` argument)
Saving 7 x 7 in image
Warning messages:
1: In write.table(metagene_start_stop_read_counts_data, file = tsv_file_path,  :
  appending column names to file
2: In write.table(gene_poslen_counts_5start_df, file = tsv_file_path,  :
  appending column names to file
Saving 7 x 7 in image
Warning message:
In write.table(read_counts_by_length_data, file = tsv_file_path,  :
  appending column names to file
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions
Calls: ... eval -> eval -> eval -> colSums -> colSums -> <Anonymous>
In addition: Warning messages:
1: In mclapply(gene_names, function(gene) { :
  all scheduled cores encountered errors in user code
2: In mclapply(gene_names, function(gene) { :
  all scheduled cores encountered errors in user code
3: In mclapply(gene_names, function(gene) { :
  all scheduled cores encountered errors in user code
Execution halted

The [87/eda624] error contains the same information. 

To solve this, we need to compare the yaml file with the 2.1 yaml and Brar et al., 2012 yaml file to see if this is the issue. 

It is unlikely to be a problem with the fasq files but we will keep this in mind. 

The Brar et al., (2012) dataset ran successfully and therefore, we do not think that it is a problem with the code.

**Comment by Maberuiz** [comment]
Similar issue in closed issue #94

**Comment by B209678-2021** [comment]
Ran the Wallace et al. 2020 Cryptococcus neoformans 'JEC21' example dataset again using the fungi/cryptococcus/Wallace_2020_JEC21_2-samples_10p_up12dwn9_CDS_120bpL_120bpR_config_2-1.yaml file but had the same error again. 

Running riboviz on the Wallace_2020_H99 Cryptococcus dataset instead and the Muzzey_2014 Candida albicans RPF dataset to see if it is maybe a problem with the Wallace_2020_JEC21 fasta files as suggested in #94.

**Comment by B209678-2021** [comment]
Ran the Wallace_2020_H99 Cryptococcus dataset but had the same error:

[bc/f0a343] Submitted process > buildIndicesORF (H99_CDS_with_120bputrs)
[e2/98ab5e] Submitted process > cutAdapters (HdAGO1)
[50/8fa337] Submitted process > cutAdapters (H99r2)
[e3/99bd59] Submitted process > buildIndicesrRNA (H99_rRNA)
[32/cd7519] Submitted process > cutAdapters (HdGWO1)
[a5/8e2a1e] Submitted process > cutAdapters (H99r1)
[3f/0ce92c] Submitted process > createVizParamsConfigFile
[bd/08c75c] Submitted process > createInteractiveVizParamsConfigFile
[92/ee17f3] Submitted process > hisat2rRNA (H99r1)
[41/0960b0] Submitted process > hisat2rRNA (H99r2)
[b7/1be3d5] Submitted process > hisat2rRNA (HdAGO1)
[8f/7aa056] Submitted process > hisat2rRNA (HdGWO1)
[93/9b10a2] Submitted process > hisat2ORF (H99r1)
[a7/f1e5f0] Submitted process > hisat2ORF (H99r2)
[2c/4077c9] Submitted process > hisat2ORF (HdAGO1)
[fa/8209f0] Submitted process > hisat2ORF (HdGWO1)
[f2/36c073] Submitted process > trim5pMismatches (H99r1)
[b4/9e22a7] Submitted process > trim5pMismatches (H99r2)
[f9/4c1310] Submitted process > samViewSort (H99r1)
[28/aec349] Submitted process > trim5pMismatches (HdAGO1)
[22/bf1e20] Submitted process > trim5pMismatches (HdGWO1)
[cc/ddec8a] Submitted process > outputBams (H99r1)
[bd/f30b66] Submitted process > makeBedgraphs (H99r1)
[3e/4cffdd] Submitted process > bamToH5 (H99r1)
[f3/bd6a2f] Submitted process > samViewSort (H99r2)
[a0/127d3b] Submitted process > samViewSort (HdAGO1)
[30/e282b8] Submitted process > samViewSort (HdGWO1)
[c7/dc138a] Submitted process > outputBams (H99r2)
[76/908391] Submitted process > makeBedgraphs (H99r2)
[1c/97fac7] Submitted process > bamToH5 (H99r2)
[95/6502c6] Submitted process > generateStatsFigs (H99r1)
[34/baeeb1] Submitted process > outputBams (HdAGO1)
[c6/1581ff] Submitted process > makeBedgraphs (HdAGO1)
[53/5df2d4] Submitted process > bamToH5 (HdAGO1)
[c4/7dd6c3] Submitted process > outputBams (HdGWO1)
[bb/2b2e52] Submitted process > makeBedgraphs (HdGWO1)
[b6/331370] Submitted process > bamToH5 (HdGWO1)
[c5/4ca315] Submitted process > generateStatsFigs (H99r2)
[95/6502c6] NOTE: Process `generateStatsFigs (H99r1)` terminated with an error exit status (1) -- Error is ignored
[59/b6ac24] Submitted process > generateStatsFigs (HdAGO1)
[71/3fb362] Submitted process > generateStatsFigs (HdGWO1)
[c5/4ca315] NOTE: Process `generateStatsFigs (H99r2)` terminated with an error exit status (1) -- Error is ignored
[59/b6ac24] NOTE: Process `generateStatsFigs (HdAGO1)` terminated with an error exit status (1) -- Error is ignored
[71/3fb362] NOTE: Process `generateStatsFigs (HdGWO1)` terminated with an error exit status (1) -- Error is ignored

The Muzzey_2014 Candida albicans RPF dataset ran successfully so it might be an issue with the Cryptococcus data files because cannot see any issues with the Yaml file. Sophie had the same issue last year #94 but we are not entirely clear on what the problem was or how it was fixed. Could be a problem with the files?

The W-Cn-H99_2020-19748728-node3g25.ecdf.ed.ac.uk.e file showed a 'write error' with the files:

WARNING: If you use conda to create environments, your home directory may fill up. Please see our documentation at 
 https://www.wiki.ed.ac.uk/display/ResearchServices/Anaconda for advice.
mkdir: cannot create directory ‘Wallace_2020_H99’: File exists
mkdir: cannot create directory ‘Wallace_2020_H99/input’: File exists
spots read      : 138,051,092
reads read      : 138,051,092
reads written   : 138,051,092
spots read      : 172,330,085
reads read      : 172,330,085
reads written   : 172,330,085
spots read      : 160,189,934
reads read      : 160,189,934
reads written   : 160,189,934
spots read      : 169,471,324
reads read      : 169,471,324
reads written   : 169,471,324
pigz: abort: write error on SRR9336389.fastq.gz (Inappropriate ioctl for device)

**Comment by B209678-2021** [comment]
We have opened a new branch called 'cryptococcus-error-109' 

Issue ticket #79 suggests that 'FlankCDS' from the header of the fasta files is the problem. 

Modified the fasta file to remove 'FlankCDS' from the header of the fasta file:

sed 's/ FlankCDS//g' $filename > modified$file.name

Temporarily modified the yaml files to match the names of the new fasta files. 

Running the Wallace et al. 2020 Cryptococcus neoformans 'JEC21' example dataset and Wallace_2020_H99 Cryptococcus dataset again.

**Comment by Maberuiz** [comment]
Wallace et al. 2020 Cryptococcus neoformans 'JEC21' example dataset run successfully, fasta file renamed back to normal and reference in yaml corrected to be back to normal again (commits still locally, have to be pushed).

Now checking all the fasta files in fungi to check no more 'FlankCDS' appear in the headings of each sequence

**Comment by FlicAnderson** [comment]
@Maberuiz this sounds like a great bit of problem solving and I think checking the rest of the files is a good idea. 

Once you're happy with the fix in this branch, we can maybe go through the process of creating a pull request and the review/merge process on Tuesday with @B209678-2021 ?

**Comment by Maberuiz** [comment]
Yes, sounds good. @B209678-2021 is running Wallace_2020_H99 Cryptococcus dataset to double check both cryptococcus datasets now work. I will get all the commits ready and push them to the branch in github so we can do the pull request and the review/merge on Tuesday.

**Comment by Maberuiz** [comment]
I found the ''FlankCDS' in neurospora's FASTA file (NC12_CDS_with_120bputrs.fa). Will delete the string and try running the dataset. The rest of the FASTA files are clean.

**Comment by Maberuiz** [comment]
Wallace_2020_H99 Cryptococcus dataset finished successfully. Both fasta files have been modified and all changes have been pushed in the github version of the branch cryptococcus-error-109.

Now I will create a new branch called neurospora-error-109 to modify that fasta file and check everything is working properly.

**Comment by FlicAnderson** [comment]
Think this is ready to Pull Request both branches & review! Perhaps @FlicAnderson and @ewallace could review these PRs once they've been created.

**Comment by FlicAnderson** [comment]
@Eldonoho99 will create pull request for `neospora-error-109` branch (similar to PR #111)
