### ISSUE TITLE
Prepare Premal's yeast data for use with RiboViz

### ISSUE THREAD

**Issue by mikej888** [riboviz/example-datasets#14]
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE124428

Requires UMI handling and deduplication.

**Comment by ewallace** [comment]
At 9 Sept dev meeting we suggested @acope3 attack this first.

**Comment by acope3** [comment]
Update: tried running riboviz on dataset found at [GSE124428](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE124428) (species: Saccharomyces cerevisiae) with 9 total measurements. Demultiplexing appeared to work, but only a subset of the measurements were actually processed any further. This turned out to be due to Issue [#214](https://github.com/riboviz/riboviz/issues/214). After fixing this issue in my local version of the code, riboviz processed all 9 measurements successfully. Will begin working on adding this to example-datasets.

**Comment by acope3** [comment]
Submitted pull request #17
