### ISSUE TITLE
Add Jan et al 2014 and Lareau et al 2014

### ISSUE THREAD

**Issue by swinterbourne** [riboviz/example-datasets#55]
Add the Jan et al 2014 and Lareau et al 2014 datasets with the aim of replicating the results of the 17 inhibitory codon pairs defined by Gamble et al 2016 in the paper **Adjacent Codons Act in Concert to Modulate Translation Efficiency in Yeast** [link](https://www.cell.com/cell/fulltext/S0092-8674(16)30674-2?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867416306742%3Fshowall%3Dtrue)

According to the [supplementary methods](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4967012/bin/NIHMS800838-supplement-5.pdf), Gamble et al used the datasets:
1. Sec63mVenusBirA_-CHX_1minBiotin_input [GSM1495519](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1495519) from [Jan et al., 2014](https://science.sciencemag.org/content/346/6210/1257521.long)
2. Replicated results with Replicate 1 [GSM1406453](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1406453), Replicate 2 [GSM1406454](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1406454) and Replicate 3 [GSM1406455](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1406455) from [Lareau et al 2014](https://elifesciences.org/articles/01257)

**Comment by swinterbourne** [comment]
Both Jan et al 2014 and Lareau et al 2014 used the adaptor sequence `CTGTAGGCACCATCAAT` which was referred to as "Universal miRNA cloning linker from New England Biolabs, Ipswich, MA (cat# S1315S)" in the [supplementary materials](https://science.sciencemag.org/highwire/filestream/596204/field_highwire_adjunct_files/0/Jan.SM.pdf) of Jan et al 2014 and the Lareau et al 2014 paper. 

Jan et al 2014 was run through Eddie and produced clean output files. 
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6018694/3nt_periodicity.pdf)
[3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/6018696/3ntframe_propbygene.pdf)
[codon_ribodens.pdf](https://github.com/riboviz/example-datasets/files/6018701/codon_ribodens.pdf)
[features.pdf](https://github.com/riboviz/example-datasets/files/6018703/features.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/6018698/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6018699/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6018707/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6018708/startcodon_ribogridbar.pdf)

Replicate 1 from Lareau et al 2014 produced output files which indicate UMIs are likely present.
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6018712/3nt_periodicity.pdf)
[3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/6018713/3ntframe_propbygene.pdf)
[codon_ribodens.pdf](https://github.com/riboviz/example-datasets/files/6018714/codon_ribodens.pdf)
[features.pdf](https://github.com/riboviz/example-datasets/files/6018715/features.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/6018717/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6018718/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6018719/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6018720/startcodon_ribogridbar.pdf)

**Comment by swinterbourne** [comment]
As the outputs from Jan et al 2014 appear clean and there are no apparent issues, this dataset has likely been processed successfully. As the outputs from Lareau et al 2014 require some troubleshooting, further progress on this will be reported in a separate issue ticket #58.

**Comment by ewallace** [comment]
@lianafaye, would mind checking the outputs above for Lareau et al 2014? Is it giving the right ribogrid plots for your dataset?

Nice work from @swinterbourne! Please do upload your config files to a branch, and then can put in a pull request.

Please also update the `fungi/README.md` file to include these.

**Comment by lianafaye** [comment]
I'll reply on #58 but this looks correct to me.

**Comment by FlicAnderson** [comment]
(Moving this comment over from #58 where I added it by mistake) 

After running this successfully on 'develop', I've run it through the currently unmerged `rmarkdown-outputs-193` branch (last commit: [ac8fc35](https://github.com/riboviz/riboviz/commit/ac8fc355aeca3e095c75cdbbbf8f1e6c3df99ab4)) to get the .html output reports. Happy for @swinterbourne to merge it :)

Here they are (converted to .pdf for upload here): 
[Replicate-1_output_report.pdf](https://github.com/riboviz/example-datasets/files/6206705/Replicate-1_output_report.pdf)
[Replicate-2_output_report.pdf](https://github.com/riboviz/example-datasets/files/6206706/Replicate-2_output_report.pdf)
[Replicate-3_output_report.pdf](https://github.com/riboviz/example-datasets/files/6206707/Replicate-3_output_report.pdf)

Note: After running these, I spotted the plotting code printing to the .html for the last plot as a result of the wrong block visibility setting in `AnalysisOutputs.Rmd`. This was fixed in commit 47ff634 as part of work to finish up [riboviz/#193](https://github.com/riboviz/riboviz/issues/193). 

Extra Note: running these & comparing them to @swinterbourne 's .pdfs pointed out the fact that on the .html output plots, 3' and 5' are in the wrong order!  This is yet to fix, since it's only just discovered.
