### ISSUE TITLE
Add Lareau et al 2014 Saccharomyces cerevisiae - troubleshooting

### ISSUE THREAD

**Issue by swinterbourne** [riboviz/example-datasets#58]
Continuation of issue ticket #55 

**Overarching goal:** Add datasets from [Lareau et al 2014](https://elifesciences.org/articles/01257) with the aim of replicating the results of the 17 inhibitory codon pairs defined by Gamble et al 2016 in the paper **Adjacent Codons Act in Concert to Modulate Translation Efficiency in Yeast** ([link](https://www.cell.com/cell/fulltext/S0092-8674(16)30674-2?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867416306742%3Fshowall%3Dtrue))

**Goal for this issue ticket:** troubleshoot what is causing the outputs to be so irregular.

Replicate 1 [GSM1406453](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1406453)
Replicate 2 [GSM1406454](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1406454) 
Replicate 3 [GSM1406455](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1406455)

The adaptor sequence used was `CTGTAGGCACCATCAAT` which was referred to as "Universal miRNA cloning linker from New England Biolabs, Ipswich, MA (cat# S1315S)" ([link](https://international.neb.com/products/s1315-universal-mirna-cloning-linker#Product%20Information)) in the Lareau et al 2014 paper.

The output graphs for Replicate 1 indicate something went wrong. For example: There are aberrant peaks in the 3nt_periodicity graph. There are two peaks present in the read_length graph. The startcodon_ribogrid counts are overall close to zero. 

The output graphs for Replicate 1 are listed below: 
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6030505/3nt_periodicity.pdf)
[3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/6030506/3ntframe_propbygene.pdf)
[codon_ribodens.pdf](https://github.com/riboviz/example-datasets/files/6030507/codon_ribodens.pdf)
[features.pdf](https://github.com/riboviz/example-datasets/files/6030508/features.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/6030510/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6030511/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6030512/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6030504/startcodon_ribogridbar.pdf)

The output graphs for Replicate 2 also indicate something went wrong. For example: 3nt_periodicity graph lacks clear periodicity. The pos_sp_rpf_norm_reads graph are aberrant. Again, there are two peaks present in the read_length graph. The startcodon_ribogrid counts are overall close to zero. 

The output graphs for Replicate 2 are listed below: 
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6030737/3nt_periodicity.pdf)
[3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/6030727/3ntframe_propbygene.pdf)
[codon_ribodens.pdf](https://github.com/riboviz/example-datasets/files/6030728/codon_ribodens.pdf)
[features.pdf](https://github.com/riboviz/example-datasets/files/6030729/features.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/6030732/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6030733/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6030734/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6030736/startcodon_ribogridbar.pdf)

The output graphs for Replicate 3 are also weird. For example: There are aberrant peaks in the 3nt_periodicity graph. The pos_sp_rpf_norm_reads graph is also very irregular. A peak is present at 20 nt in the read_length graph. The startcodon_ribogridbar is very irregular and seems to be lacking a lot of reads. 

The output graphs for Replicate 3 are listed below: 
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6030745/3nt_periodicity.pdf)
[3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/6030746/3ntframe_propbygene.pdf)
[codon_ribodens.pdf](https://github.com/riboviz/example-datasets/files/6030747/codon_ribodens.pdf)
[features.pdf](https://github.com/riboviz/example-datasets/files/6030748/features.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/6030756/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6030742/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6030743/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6030744/startcodon_ribogridbar.pdf)

The majority of the alignments were lost, according to the read_counts.tsv file:
Replicate 1 went from 34 687 486 to 7 022 487 reads
Replicate 2 went from 35 838 179 to 5 900 551 reads
Replicate 3 went from 54 362 276 to 2 789 857 reads

**Comment by lianafaye** [comment]
Hi @swinterbourne @ewallace  - happy to fill in info on the Lareau 2014 data. Those footprints come from this paper: https://elifesciences.org/articles/01257

in which we showed that ribosomes protect two footprint sizes, ~20 nt and ~28 nt. This size range shifts depending on which translation inhibitor drugs are used. When people use cycloheximide to block translation, they get only 28 nt footprints, and because the very first ribosome profiling experiments used that drug, that's what the field standardized on.

So, seeing two footprint-size peaks is exactly expected.

For a few reasons, the data in our paper don't match up with tAI etc as cleanly as some experiments -- because we didn't use any inhibitors to freeze ribosomes in place, and because of how the counts are divided across two footprint sizes that reflect different stages of the physical process of translation elongation.

I've glanced through the files and they look ok. For instance, if you remove the really big peak at the start codon, the rest of the data have pretty clear 3 nt periodicity, it's just compressed on the plot by that one big peak. But let me know if there are remaining oddities - it's totally possible our data might break some aspects of the pipeline.

**Comment by FlicAnderson** [comment]
After running this successfully on 'develop', I've run it through the currently unmerged `rmarkdown-outputs-193` branch (last commit: [ac8fc35](https://github.com/riboviz/riboviz/commit/ac8fc355aeca3e095c75cdbbbf8f1e6c3df99ab4)) to get the .html output reports. Happy for @swinterbourne to merge it :)

Here they are (converted to .pdf for upload here): 
[Replicate-1_output_report.pdf](https://github.com/riboviz/example-datasets/files/6206705/Replicate-1_output_report.pdf)
[Replicate-2_output_report.pdf](https://github.com/riboviz/example-datasets/files/6206706/Replicate-2_output_report.pdf)
[Replicate-3_output_report.pdf](https://github.com/riboviz/example-datasets/files/6206707/Replicate-3_output_report.pdf)

Note: After running these, I spotted the plotting code printing to the .html for the last plot as a result of the wrong block visibility setting in `AnalysisOutputs.Rmd`. This was fixed in commit 47ff634 as part of work to finish up [riboviz/#193](https://github.com/riboviz/riboviz/issues/193). 

Extra Note: running these & comparing them to @swinterbourne 's .pdfs pointed out the fact that on the .html output plots, 3' and 5' are in the wrong order!  This is yet to fix, since it's only just discovered.

**Comment by ewallace** [comment]
> 3' and 5' are in the wrong order

`factor(., levels = c("5'","3'")`

**Comment by ewallace** [comment]
This looks so good! Both the dataset and the .html
